# Site settings
title: Multiplex
email: info@multiplexcy.com
url: https://multiplexcy.com
description: "The end has come to the unnecessary stressing and worrying. Multiplex's revolutionary stress cube - the s-cube - promises to relieve your stress immediately, with each side featuring a different gadget to enjoy. From switches to buttons and analogue sticks, we can guarantee you that you will never get bored of this incredible gadget. Stay tuned for more!"
background-image: intro_bg.jpg

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/MultiplexCyprus
  - title: facebook
    url: https://www.facebook.com/MultiplexCyprus/
  - title: instagram
    url: https://www.instagram.com/multiplex_cyprus/

# Build settings
markdown: kramdown
permalink: pretty
